apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: xrs.example.crossplane.io
spec:
  group: example.crossplane.io
  names:
    kind: XR
    plural: xrs
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              widgets:
                type: integer
          status:
            type: object
            properties:
              widgets:
                type: integer
